-- MySQL Script generated by MySQL Workbench
-- Sun Oct  8 21:56:09 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema sportal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sportal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sportal` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `sportal`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportal`.`users` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `e_mail` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `age` INT(11) NULL,
  `avatar` BLOB NULL DEFAULT NULL,
  `is_registred` TINYINT(4) NULL DEFAULT NULL,
  `password` VARCHAR(45) NOT NULL,
  `isBanned` TINYINT NOT NULL DEFAULT 0,
  `date_time_registered` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `idx_users_name` (`name` ASC),
  UNIQUE INDEX `e_mail_UNIQUE` (`e_mail` ASC),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'age<16 not allowed to see shocking news:)\nsuggest comments  has an user\nis_banned int?\nadd favorite_category?\nadd role : admin, regular, banned ?';


-- -----------------------------------------------------
-- Table `mydb`.`friends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`friends` (
  `user_id` INT NOT NULL,
  `users_user_id` INT(11) NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_friends_users_idx` (`users_user_id` ASC),
  CONSTRAINT `fk_friends_users`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `sportal`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Author/Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Author/Admin` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `avatar` BLOB NULL,
  `articles_counter` INT NULL,
  `description` VARCHAR(100) NULL,
  `e-mail` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

USE `sportal` ;

-- -----------------------------------------------------
-- Table `sportal`.`subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportal`.`subject` (
  `object_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `commented` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`object_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sportal`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportal`.`categories` (
  `category_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sportal`.`sub_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportal`.`sub_category` (
  `sub_category_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `category` INT(11) NOT NULL,
  PRIMARY KEY (`sub_category_id`),
  INDEX `category_idx` (`category` ASC),
  CONSTRAINT `category`
    FOREIGN KEY (`category`)
    REFERENCES `sportal`.`categories` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sportal`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportal`.`article` (
  `article_id` INT(11) NOT NULL AUTO_INCREMENT,
  `sub_category` INT(11) NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `content` LONGTEXT NOT NULL,
  `date` DATE NOT NULL,
  `impressions` INT(11) NULL DEFAULT NULL,
  `isLeading` TINYINT NULL DEFAULT 0,
  `object_id` INT(11) NULL DEFAULT NULL,
  `Author/Admin_id` INT NOT NULL,
  PRIMARY KEY (`article_id`, `Author/Admin_id`),
  INDEX `title` USING BTREE (`title` ASC),
  INDEX `categori_id_idx` (`sub_category` ASC),
  INDEX `object_id_idx` (`object_id` ASC),
  INDEX `idx_article_title` (`title` ASC),
  INDEX `fk_article_Author/Admin1_idx` (`Author/Admin_id` ASC),
  UNIQUE INDEX `article_id_UNIQUE` (`article_id` ASC),
  CONSTRAINT `object_id`
    FOREIGN KEY (`object_id`)
    REFERENCES `sportal`.`subject` (`object_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sub_category`
    FOREIGN KEY (`sub_category`)
    REFERENCES `sportal`.`sub_category` (`sub_category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_Author/Admin1`
    FOREIGN KEY (`Author/Admin_id`)
    REFERENCES `mydb`.`Author/Admin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'longtext check\ncategories table\nnot sure about comments\n/where to add sub_category it has to be from category but not sure\nstatus_id breaking, top, shock:)\nobject_id Levski, CSKA...\n...add subscribers may be\nremoved tag, picture and video because  both refer to article_id';


-- -----------------------------------------------------
-- Table `sportal`.`picture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportal`.`picture` (
  `picture_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `content` BLOB NOT NULL,
  PRIMARY KEY (`picture_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sportal`.`article_pics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportal`.`article_pics` (
  `article_id` INT(11) NOT NULL,
  `picture_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`article_id`),
  INDEX `pucture_idx` (`picture_id` ASC),
  CONSTRAINT `article`
    FOREIGN KEY (`article_id`)
    REFERENCES `sportal`.`article` (`article_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pucture`
    FOREIGN KEY (`picture_id`)
    REFERENCES `sportal`.`picture` (`picture_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sportal`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportal`.`tags` (
  `tag_id` INT(11) NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`tag_id`),
  UNIQUE INDEX `content_UNIQUE` (`content` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sportal`.`article_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportal`.`article_tags` (
  `article_id` INT(11) NOT NULL,
  `tag_id` INT(11) NOT NULL,
  PRIMARY KEY (`article_id`, `tag_id`),
  INDEX `tag_idx` (`tag_id` ASC),
  CONSTRAINT `articleT`
    FOREIGN KEY (`article_id`)
    REFERENCES `sportal`.`article` (`article_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tag`
    FOREIGN KEY (`tag_id`)
    REFERENCES `sportal`.`tags` (`tag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sportal`.`video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportal`.`video` (
  `video_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `content` BLOB NOT NULL,
  PRIMARY KEY (`video_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sportal`.`article_videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportal`.`article_videos` (
  `article_id` INT(11) NOT NULL,
  `video_id` INT(11) NOT NULL,
  PRIMARY KEY (`video_id`, `article_id`),
  INDEX `article_id_idx` (`article_id` ASC),
  CONSTRAINT `articleV_id`
    FOREIGN KEY (`article_id`)
    REFERENCES `sportal`.`article` (`article_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `video_id`
    FOREIGN KEY (`video_id`)
    REFERENCES `sportal`.`video` (`video_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sportal`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportal`.`comments` (
  `comment_id` INT(11) NOT NULL AUTO_INCREMENT,
  `author` INT(11) NOT NULL,
  `article` INT(11) NOT NULL,
  `content` VARCHAR(200) NULL DEFAULT NULL,
  `answer` INT(11) NULL DEFAULT NULL,
  `likes` INT(11) NULL DEFAULT 0,
  `dislikes` INT(11) NULL DEFAULT 0,
  `time_date` DATETIME NOT NULL,
  `isApproved` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`comment_id`),
  INDEX `user_id_idx` (`author` ASC),
  INDEX `answer_idx` (`answer` ASC),
  INDEX `article_id_idx` (`article` ASC),
  CONSTRAINT `answer`
    FOREIGN KEY (`answer`)
    REFERENCES `sportal`.`comments` (`comment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `article_id`
    FOREIGN KEY (`article`)
    REFERENCES `sportal`.`article` (`article_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id`
    FOREIGN KEY (`author`)
    REFERENCES `sportal`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sportal`.`regions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportal`.`regions` (
  `region_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`region_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
